# Generated by Django 5.2.9 on 2025-12-19 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('percentage', 'Foiz'), ('fixed', 'Belgilangan summa'), ('free_delivery', 'Bepul yetkazish')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('per_user_limit', models.IntegerField(default=1)),
                ('used_count', models.IntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coupons.coupon')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
